version: '2'
services:
  app:
    image: 'fintech-payment-api-sqd11b:latest'
    build:
      context: .
    ports:
      - "8081:8080"
    container_name: fintechApp
    depends_on:
      - fintechDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fintechDb:5432/fintech-app
      - SPRING_DATASOURCE_USERNAME=fintech-app
      - SPRING_DATASOURCE_PASSWORD=fintech-app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  fintechDb:
    image: 'postgres:latest'
    container_name: fintechDb
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=fintech-app
      - POSTGRES_PASSWORD=fintech-app